name: nocab
description: A file sharing app between your devices.

publish_to: 'none' 

version: 0.3.1+1

environment:
  sdk: ">=2.18.0-271.7.beta <3.0.0"

dependencies:
  animations: ^2.0.7
  crypto: ^3.0.2
  cupertino_icons: ^1.0.5
  device_info_plus: ^8.0.0
  file: ^6.1.4
  file_picker: ^5.2.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_svg: ^1.1.6
  vibration: ^1.7.6
  mobile_scanner:
    git:
      url: https://github.com/juliansteenbakker/mobile_scanner.git
      ref: master
  open_filex: ^4.3.2
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  provider: ^6.0.5
  path: ^1.8.2
  package_info_plus: ^3.0.2
  http: ^0.13.5
  url_launcher: ^6.1.7
  easy_localization: ^3.0.1
  flutter_animate: ^2.0.1
  receive_sharing_intent:
    git:
      url: https://github.com/nocab-transfer/receive_sharing_intent.git
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  uuid: ^3.0.7
  share_plus: ^6.3.0
  nocab_core:
    git:
      url: https://github.com/nocab-transfer/nocab-core.git
  network_info_plus: ^3.0.1
  connectivity_plus: ^3.0.2

dev_dependencies:
  isar_generator: ^3.0.2
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/ic_launcher.png"
  adaptive_icon_background: "assets/icon/application_background.png"
  adaptive_icon_foreground: "assets/icon/application_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/human.svg
    - assets/images/paperplane.svg
    - assets/images/airplane.svg
    - assets/images/history_empty_state.svg
  fonts:
    - family: VarelaRound
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
