name: nocab
description: A file sharing app between your devices.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.18.0-165.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  device_info_plus: ^3.2.3
  file_picker: ^4.5.1
  flutter_svg: ^1.0.3
  crypto: ^3.0.1
  provider: ^6.0.2
  mobile_scanner: 
    git:
      url: https://github.com/juliansteenbakker/mobile_scanner.git
      ref: master
  animations: ^2.0.2
  flutter_bloc: ^8.0.1
  flutter_vibrate: ^1.3.0
  permission_handler: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.3"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/ic_launcher.png"
  adaptive_icon_background: "assets/icon/application_background.png"
  adaptive_icon_foreground: "assets/icon/application_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/human.svg
    - assets/images/paperplane.svg