name: nocab
description: A file sharing app between your devices.

publish_to: 'none' 

version: 0.0.2+1

environment:
  sdk: ">=2.18.0-271.7.beta <3.0.0"

dependencies:
  animations: ^2.0.2
  crypto: ^3.0.1
  cupertino_icons: ^1.0.2
  device_info_plus: ^4.0.0
  file: ^6.1.4
  file_picker: ^5.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_svg: ^1.0.3
  flutter_vibrate: ^1.3.0
  mobile_scanner:
    git:
      url: https://github.com/juliansteenbakker/mobile_scanner.git
      ref: master
  open_filex: ^4.1.1
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  provider: ^6.0.2
  path: ^1.8.2

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/ic_launcher.png"
  adaptive_icon_background: "assets/icon/application_background.png"
  adaptive_icon_foreground: "assets/icon/application_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/human.svg
    - assets/images/paperplane.svg
    - assets/images/airplane.svg
